### ISSUE TITLE
WorkingWeek Wired Class Hierarchie 

### ISSUE THREAD

**Issue by MehrCurry** [Appendium/objectlabkit#18]
I want to calculate with JDK8 LocalDates and a WorkingWeek from Monday to Saturday.

I tried to create a WorkingWeek instance this way:

```groovy
    Jdk8WorkingWeek getWorkingWeek() {
        new Jdk8WorkingWeek().withWorkingDayFromCalendar(true, Calendar.SATURDAY)
    }
```

But the type information is lost. I'll get back in Instance of WorkingWeek which cannot be feed into
`LocalDateKitCalculatorsFactory`.

Perhaps i missed something. What is the intended way to create am Mo-Sa WorkingWeek?

**Comment by benoitx** [comment]
Hi,
You can set the Working Week on an existing calendar it seems.
I enclose an example.

I hope this helps

Benoit

`import java.time.DayOfWeek;
import java.time.LocalDate;

import net.objectlab.kit.datecalc.jdk8.Jdk8WorkingWeek;
import net.objectlab.kit.datecalc.jdk8.LocalDateCalculator;
import net.objectlab.kit.datecalc.jdk8.LocalDateKitCalculatorsFactory;

public class ObjectLabKitJdk8Test {
    public static void main(final String[] args) {
        final Jdk8WorkingWeek ww = new Jdk8WorkingWeek().withWorkingDayFromDateTimeConstant(true, DayOfWeek.SATURDAY);

        final LocalDateCalculator forwardCalculator = LocalDateKitCalculatorsFactory.forwardCalculator("blabla");
        forwardCalculator.setStartDate(LocalDate.parse("2017-03-18")); // a Saturday
        System.out.println(forwardCalculator.getCurrentBusinessDate()); // still using the default week, so it should move to Monday

        forwardCalculator.setWorkingWeek(ww);
        forwardCalculator.setStartDate(LocalDate.parse("2017-03-18")); // a Saturday
        System.out.println(forwardCalculator.getCurrentBusinessDate()); // Now Saturday is a work day, it should stay there
    }
}
`

**Comment by MehrCurry** [comment]
Thank for the hints.
