### ISSUE TITLE
How  to define my WorkingWeek ?

### ISSUE THREAD

**Issue by raftonsea** [Appendium/objectlabkit#23]
For my scenario ,  " Non-working Day  (eg Saturday)   "  sometime needs to be a workday and  sometime Monday needs to be a  Non-working Day ( I can define my HolidayCalendar so solve this ).   I know I can  use DateCalculator.setWorkingWeek(WorkingWeek week) to define my WorkingWeek  , but I want to query db or redis  to dedicate weather a  Date is a   " the  Saturday  is a workday" .  But I did't find any examples. SO , can you give me some hints?

**Comment by benoitx** [comment]
Hi

First of all, great that you are considering ObjectLab Kit/Calendar.  I hope that I understood your requirements.  I would say that the concept of a WorkingWeek is NOT what I would use in your case, WorkingWeek is meant to be immutable once decided (e.g. Saturdays might ALWAYS be working days in some markets).  Having said that, there is a solution for you.

The concept of Calendar or Non Working days which could come from your REDIS or other database, I would therefore do this:
1) Use a WorkingWeek which includes both Saturdays and Mondays as working days
2) Create a list of Holidays/non-working days from your DB and give it to the Calculator.

See this example:
https://gist.github.com/benoitx/0b05de796fe94ebc04c2#file-date-calc-using-joda-localdate-java

I hope this helps,
Regards
Benoit

**Comment by raftonsea** [comment]
Ok , i see . Thanks a lot.

**Comment by benoitx** [comment]
Apologies. wrong issue.
