### ISSUE TITLE
Upgrade to org.apache.commons.lang3 for StringUtil.java?

### ISSUE THREAD

**Issue by zukunft** [Appendium/objectlabkit#29]
Maybe the new version of FastDateFormat from org.apache.commons.lang3 for utils/src/main/java/net/objectlab/kit/util/StringUtil.java should be used. And also org.apache.commons.lang3.builder.StandardToStringStyle could be used.

**Comment by benoitx** [comment]
Thanks for the suggestion. will be part of 1.4.3
